### ISSUE TITLE
Test-roadmap-03

### ISSUE THREAD

**Issue by agviegas** [IFCjs/components#114]
### Describe the bug 📝

asdf

### Reproduction ▶️

asdf

### Steps to reproduce 🔢

asdf

### System Info 💻

```shell
asdf
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

asdfadfa

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
